"""Add Geolocation model

Revision ID: 11d9ad0f9832
Revises: 
Create Date: 2025-03-14 23:28:45.067061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '11d9ad0f9832'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geolocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('continent_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('continent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('longitude', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geolocation')
    # ### end Alembic commands ###
