"""Add created_at and url fields to Geolocation

Revision ID: 14d8408367c8
Revises: 11d9ad0f9832
Create Date: 2025-03-15 01:05:29.785873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '14d8408367c8'
down_revision: Union[str, None] = '11d9ad0f9832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geolocation', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('geolocation', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geolocation', 'url')
    op.drop_column('geolocation', 'created_at')
    # ### end Alembic commands ###
